### ISSUE TITLE
Apple requires all apps to support IPv6 from 1st of June

### ISSUE THREAD

**Issue by romk1n** [facebook/SocketRocket#349]
http://www.iclarified.com/55078/starting-june-1st-all-apps-submitted-to-the-app-store-must-support-ipv6only-networking

Are there any changes required to this great library ?

**Comment by nlutsenko** [comment]
Hey @romk1n, that's a great question. 
From what I recall, we get IPv6 support for free with CFNetwork (SocketRocket is based on CFStreams).
If you have a test IPv6-only network - please test it and let us know if you run into any problems.
Otherwise - I am going to test it at some point, will try my best to make it before June 1st, but can't guarantee the timing precisely.

**Comment by nlutsenko** [comment]
Just tested this on a  IPv4+IPv6 network - I was able to make this connect no problem to an IPv6 address no problem, meaning that we indeed support IPv6, hence I didn't expect otherwise since we are using CFNetwork stack.
Please open an issue if you run into any connectivity problems on IPv6 networks.

**Comment by romk1n** [comment]
Thank you for confirmation !
