### ISSUE TITLE
After upgraded CocoaPods 1.0, `#import <SocketRocket/SRWebSocket.h>` file not found.

### ISSUE THREAD

**Issue by nixzhu** [facebook/SocketRocket#381]

**Comment by jackielee527** [comment]
I also meet this issue, can anybody suggest solution?

**Comment by jackielee527** [comment]
After upgrading to cocoapods 1.0, SocketRocket is still properly running on iOS simulator, but if I am trying to run on iOS device, error is happened on this line.

`static const size_t SRDefaultBufferSize = PAGE_SIZE;`

Use of undeclared identifier 'PAGE_SIZE'

**Comment by nlutsenko** [comment]
@jackielee527, I can reproduce the last error. Submitting a fix in a moment.

**Comment by nlutsenko** [comment]
@nixzhu, can you share your Podfile here?
I've just tested locally and it looks to be properly installing and running using the latest CocoaPods.

**Comment by nixzhu** [comment]
@nlutsenko I'm working on an open source project https://github.com/CatchChat/Yep , Podfile:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def pods
    pod 'Kanna', '1.0.2'
    pod 'Navi'
    pod 'Appsee'
    pod 'Alamofire'
    pod 'DeviceGuru'
    pod '1PasswordExtension'
    pod 'KeyboardMan'
    pod 'Ruler'
    pod 'Proposer'
    pod 'FXBlurView'
    pod 'Kingfisher'
    pod 'TPKeyboardAvoiding'
    pod 'pop'
    pod 'Base64'
    pod 'SocketRocket'
    pod 'RealmSwift'
    pod 'MonkeyKing', '0.0.2'
    pod 'JPush'
    pod 'Fabric'
end

target 'Yep' do
    pods
end
```

You can test in it's develop branch if you like. Thanks!

**Comment by nlutsenko** [comment]
Perfect, thanks, that was super helpful.
Unfortunately, it built cleanly for me...
I would suggest cleaning Xcode's DerivedData (be aware that unless they are removed from trash as well they might still be open via Xcode, so please close Xcode and empty trash).
Also, it might be a good idea to completely clean the locally ignored files by running `git clean -xfd .` in the repo root (since I was able to compile on clean checkout, that might be a reason).

Let me know how it goes and whether either of these help or not.

<img width="971" alt="screen shot 2016-05-17 at 5 21 28 pm" src="https://cloud.githubusercontent.com/assets/606991/15343681/cf55fcfe-1c53-11e6-98b2-0d2e8b0392ff.png">

**Comment by nlutsenko** [comment]
Also, if they don't - I would suggest looking for something that is specific to your machine and trying to repro in a different folder or on a different laptop with a clean checkout.

**Comment by nixzhu** [comment]
@nlutsenko Clean DerivedData works. Thanks a lot!
