### ISSUE TITLE
Error 1009

### ISSUE THREAD

**Issue by AncAinu** [facebook/SocketRocket#385]
Hi one of my user got an error 1009:

```
SRStatusCodeMessageTooBig = 1009,
 NSMutableData *frame = [[NSMutableData alloc] initWithLength:payloadLength + SRFrameHeaderOverhead];
    if (!frame) {
        [self closeWithCode:SRStatusCodeMessageTooBig reason:@"Message too big"];
        return;
    }
```

The user says the error happens only in 3G and not WiFi.
Any idea how it can be possible ?
User have an iPhone 6, iOS 9.

It's one user in some hundreds of thousands.

**Comment by nlutsenko** [comment]
We are opting out here because we failed to allocate data that was required to send the frame. We are sending it in chunks over the wire anyway, but need the full buffer to be in memory, so we can form the headers and send them first. The only thing that I could suggest - try splitting the payload into smaller chunks, so we don't need the huge frame buffer. 

P.S. I actually am glad that you were able to hit this error, since otherwise - we would probably get into very inconsistent state, where we are trying to construct a buffer, failing and then sending a malformed frame to the server.

@AncAinu, overall, some actionables:
- Add the size constraint on the frame that you are about to send, so you can split the very large frame into smaller ones.
- If it works and you never see this error again - awesome.
- If it doesn't and you still see it - a repro case or more information about the payload would be super helpful here.
- Also, in case you think I missed something, please, feel free to reopen this issue. :grin:

**Comment by AncAinu** [comment]
Hello,

It was a false alarm, it's not your lib that gives the error but NSURLErrorNotConnectedToInternet so nothing liked here, sorry guys
