### ISSUE TITLE
Plans for 0.5.2/0.6.0 release?

### ISSUE THREAD

**Issue by jtreanor** [facebook/SocketRocket#396]
Its great to see this SocketRocket being actively maintained once again 😄 

Since 0.5.1, there have been [many great additions] (https://github.com/facebook/SocketRocket/compare/0.5.1...master).

Are there any plans to include these changes in a new release in the near future?

Does Facebook intend on sharing their plans/roadmap for SocketRocket going forward? It would be great to have visibility on this.

**Comment by nlutsenko** [comment]
Hey @jtreanor, that is a wonderful question!
Here is the rough roadmap/plan that I have so far:
- Battletest and polish 0.6.0 (the current next release) in the next week or so, so we can make sure that everything works as expected as well as the new APIs/deprecations are the right choice. I am pretty sure they are so far, but want to re-evaluate these, as adding APIs/deprecations are always a big choice.
- Enable autobahn tests on Travis-CI. Most of the work here is done, just need to make sure the environment properly sets itself up when running on Travis.
- Add HTTP/HTTPS proxy support. There is a PR for it already from the community, and since this is a one of the big feature requests - adding support for it would be just wonderful.
- Add support for currently unsupported edge-casey autobahn tests 6.4.2 and 6.4.4
- Add compression support, which is the new set of autobahn tests that we don't yet support
- Add performance testing around changes, most likely via XCTest.
- Rinse/cleanup/repeat

I expect this roadmap to span across few weeks, maybe more.
Also, if there is anything you think would be a great addition to SocketRocket, please open an issue!

**Comment by jtreanor** [comment]
Thanks for the detailed response @nlutsenko!

This all sounds great. I'm looking forward to seeing all the improvements and hopefully I can help by contributing 😄
