### ISSUE TITLE
 [OS_dispatch_data length]: unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by codefei** [facebook/SocketRocket#409]
when I use ios6, i got this crash stack,@nlutsenko 
<img width="1264" alt="2016-06-11 3 00 07" src="https://cloud.githubusercontent.com/assets/7637224/15983850/01a7da82-2fe7-11e6-9a93-c63b4fb3cbc8.png">

**Comment by codefei** [comment]
(lldb) po subdata
<OS_dispatch_data: leaf: 1, size: 516, data: 0x1fb88000>

**Comment by codefei** [comment]
(lldb) po subdata
<OS_dispatch_data: leaf: 1, size: 516, data: 0x1fb88000>

**Comment by nlutsenko** [comment]
@codefei, current master doesn't support iOS 6 any more at this point. We can add support for it, but I actually would recommend dropping support for iOS 6 altogether, since it probably is a small fraction of users for a huge amount of work we all need to do. For example, Facebook dropped support for iOS 6 a long time ago at this point. There is also a downside that there is no way to get iOS 6 or even iOS 7 simulators, so unless you have a device that still uses it - there is no way to test.

The biggest reason: we are using `dispatch_data_t` for buffers for performance reasons and it's bridged to `NSData` only starting from iOS 7, OS X 10.9.

Feel free to reopen if you think this is a required thing for us to support, but at this point - the next release of SocketRocket is set to support only iOS 7.0+, OS X 10.9+.

**Comment by codefei** [comment]
@nlutsenko I know many app support from ios7 now, but our app really there are a small fraction of users still already use ios6.0+. So I hope you can support ios6 if you have time to do this. I have device to do test.

Due to [SRWebSocket _pumpWriting] crash on ios6/ios7, otherwise i may use the last release version.
[https://github.com/facebook/SocketRocket/issues/339](url)


<img width="1021" alt="2016-06-17 1 18 52" src="https://cloud.githubusercontent.com/assets/7637224/16126275/0068d562-342a-11e6-8f28-59f621ee2e93.png">

<img width="1023" alt="2016-06-17 1 18 38" src="https://cloud.githubusercontent.com/assets/7637224/16126281/04145e8e-342a-11e6-9e90-7be130d4da32.png">

**Comment by mihui** [comment]
I have exactly the same issue.
