### ISSUE TITLE
How many number of connections are allowed max?

### ISSUE THREAD

**Issue by romuye123** [facebook/SocketRocket#436]

**Comment by nlutsenko** [comment]
Hey @romuye123, a very good question.
SocketRocket doesn't do anything special to limit number of connections at any given point in time.
Since we are using CFNetwork stack for network communications - I would say, as much as the system will allow us and as much as there are available file descriptors/network connections on the system (which I bet is different on iOS vs macOS vs watchOS).

Feel free to reopen/comment if you find the answer, but so far it is "as many as the system permits".
