### ISSUE TITLE
SRWebSocketDelegate functions not invoked when consuming SocketRocket from Swift

### ISSUE THREAD

**Issue by moozzyk** [facebook/SocketRocket#502]
I am trying to consume SocketRocket from a Swift app. The problem I am facing is that my SRWebSocketDelegate functions are never invoked. I can see that the websocket is opened correctly - `_readyState is set to 1` - but the `webSocketDidOpen` callback is never called. Similarly, I am able to send a string message (i.e. `send` does not throw) but the `didReceiveMessageWithString` callback is not called either.  I am probably hitting some kind of Objective-C/Swift interop issue but being new to macOS programming I can't figure this out. (In my other project where I originally experienced this I was able to set a breakpoint [here](https://github.com/facebook/SocketRocket/blob/41b57bb2fc292a814f758441a05243eb38457027/SocketRocket/Internal/Delegate/SRDelegateController.m#L52-L62)  and apparently none my callbacks were discovered). 
I tried making the class and functions public and also adding [`@objc`](https://github.com/moozzyk/WebSocketsTest/blob/master/WebSocketsTest/WebsocketDelegate.swift#L24) but it did not make a difference.

Here is my sample app: https://github.com/moozzyk/WebSocketsTest

I would appreciate any help with fixing this.

**Comment by feosuna1** [comment]
I'm not a maintainer, but I took a look at your sample app.  

SocketRocket is doing the right thing.  Your delegate object is not being strongly held anywhere.  `SRWebSocket`'s delegate is [`weak`](https://github.com/facebook/SocketRocket/blob/master/SocketRocket/SRWebSocket.h#L76) when you create your `WebSocketDelegate` object and [assign](https://github.com/moozzyk/WebSocketsTest/blob/master/WebSocketsTest/AppDelegate.swift#L34) it to `SRWebSocket`, your delegate object is immediately released because no one owns it.  You need to maintain a strong reference to your delegate object before you assign it to the `SRWebSocket` instance.

**Comment by moozzyk** [comment]
@feosuna1 - thanks a lot! 
I did not notice that the delegate is weak. Once I stored the reference to the delegate instance in a class variable my callbacks are invoked indeed. Thanks again - I really appreciate it.
